-- ============================================================================
-- Миграция Supabase: Фундаменталка / Калькуляторы Академии «Инвестиции просто»
-- Версия: 1 — initial schema (2026-05-08)
-- Запустить один раз в Supabase Studio → SQL Editor → New query → Run.
-- ============================================================================

-- ============================================================================
-- 1. EMITTERS — каталог эмитентов МосБиржи
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.emitters (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticker          TEXT UNIQUE NOT NULL,
  name            TEXT,
  emitent_id      INTEGER,            -- MOEX emitent_id (для группировки SBER+SBERP)
  inn             TEXT,
  okpo            TEXT,
  is_bank         BOOLEAN DEFAULT FALSE,
  sector          TEXT,
  description     TEXT,               -- краткая справка о компании
  edisclosure_id  TEXT,               -- идентификатор на e-disclosure.ru
  updated_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_emitters_emitent_id ON public.emitters(emitent_id);
CREATE INDEX IF NOT EXISTS idx_emitters_ticker_lower ON public.emitters(LOWER(ticker));

-- ============================================================================
-- 2. REPORT_FINANCIALS — история всех периодов МСФО
-- Никогда не перезаписывается, только растёт. Источник: e-disclosure.ru → DeepSeek.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.report_financials (
  id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  emitter_id    BIGINT REFERENCES public.emitters(id) ON DELETE CASCADE,
  ticker        TEXT,
  period_end    DATE,
  period_label  TEXT,                 -- '2024 Q4', '2024 год' и т.п.
  revenue       NUMERIC,
  net_profit    NUMERIC,
  ebitda        NUMERIC,
  op_profit     NUMERIC,
  ocf           NUMERIC,
  fcf           NUMERIC,
  raw           JSONB,                -- сырые цифры из отчёта на случай если потом нужно ещё чего
  created_at    TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_rf_emitter ON public.report_financials(emitter_id);
CREATE INDEX IF NOT EXISTS idx_rf_ticker_period ON public.report_financials(ticker, period_end DESC);

-- ============================================================================
-- 3. FUNDAMENTALS — последний срез мультипликаторов
-- Перезаписывается при выходе нового отчёта. По одной строке на тикер.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.fundamentals (
  ticker            TEXT PRIMARY KEY,
  emitter_id        BIGINT REFERENCES public.emitters(id) ON DELETE CASCADE,
  name              TEXT,
  is_bank           BOOLEAN DEFAULT FALSE,
  cap_bn_rub        NUMERIC,
  ev_bn_rub         NUMERIC,
  revenue           NUMERIC,
  net_profit        NUMERIC,
  net_op_income     NUMERIC,           -- для банков
  p_e               NUMERIC,
  p_b               NUMERIC,
  p_s               NUMERIC,
  ev_ebitda         NUMERIC,
  ebitda_margin     NUMERIC,
  debt_ebitda       NUMERIC,
  roe               NUMERIC,
  roa               NUMERIC,
  net_interest_margin NUMERIC,        -- для банков
  source            TEXT,
  updated_at        TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================================
-- 4. DIVIDENDS — история выплат + прогнозы
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.dividends (
  id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticker        TEXT NOT NULL,
  ex_date       DATE,
  period_label  TEXT,                 -- '2024 год', '12 мес', '9 мес' и т.п.
  amount        NUMERIC,              -- сумма на акцию, ₽
  yield_pct     NUMERIC,              -- доходность в момент отсечки, %
  is_paid       BOOLEAN,              -- TRUE = выплачено, FALSE = прогноз/анонс
  is_pref       BOOLEAN DEFAULT FALSE,
  raw           JSONB,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(ticker, ex_date, period_label)
);

CREATE INDEX IF NOT EXISTS idx_div_ticker ON public.dividends(ticker, ex_date DESC);

-- ============================================================================
-- 5. INSIDER_TRADES — сделки инсайдеров за 12 мес.
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.insider_trades (
  id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticker       TEXT NOT NULL,
  trade_date   DATE,
  insider_name TEXT,
  position     TEXT,
  direction    TEXT,                  -- 'buy' / 'sell'
  shares       NUMERIC,
  price        NUMERIC,
  value        NUMERIC,
  raw          JSONB,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ins_ticker ON public.insider_trades(ticker, trade_date DESC);

-- ============================================================================
-- 6. CORPORATE_EVENTS — календарь корпоративных событий на 90 дней
-- ============================================================================
CREATE TABLE IF NOT EXISTS public.corporate_events (
  id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ticker       TEXT NOT NULL,
  event_date   DATE,
  event_type   TEXT,                  -- 'отчётность', 'дивотсечка', 'ГОСА', 'СД'
  title        TEXT,
  description  TEXT,
  raw          JSONB,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_evt_ticker_date ON public.corporate_events(ticker, event_date);

-- ============================================================================
-- ROW LEVEL SECURITY
-- Публичные таблицы для чтения с anon/publishable key, изменять может только
-- secret-key (service role обходит RLS автоматически).
-- ============================================================================
ALTER TABLE public.emitters           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_financials  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fundamentals       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dividends          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insider_trades     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.corporate_events   ENABLE ROW LEVEL SECURITY;

-- Политики "everyone can SELECT" — для anon доступа из мини-аппа
DROP POLICY IF EXISTS "public_read" ON public.emitters;
CREATE POLICY "public_read" ON public.emitters
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "public_read" ON public.report_financials;
CREATE POLICY "public_read" ON public.report_financials
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "public_read" ON public.fundamentals;
CREATE POLICY "public_read" ON public.fundamentals
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "public_read" ON public.dividends;
CREATE POLICY "public_read" ON public.dividends
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "public_read" ON public.insider_trades;
CREATE POLICY "public_read" ON public.insider_trades
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "public_read" ON public.corporate_events;
CREATE POLICY "public_read" ON public.corporate_events
  FOR SELECT USING (true);

-- ============================================================================
-- ГОТОВО.
-- После запуска: вернись в Telegram — Тим зальёт в эти таблицы данные
-- (мультипликаторы из smart-lab + дивиденды из dohod).
-- ============================================================================
